# Configure the build matrix
env:
<<<<<<< HEAD
  matrix:
  - TEST=validation
  - TEST=pgsql
  - TEST=mysql
  global:
  - secure: "ZH/7h+OuJ4LsirvvoS6QIKhcduCJ02yIAQOFv9nLqDljeD2UNemha6j8CkVeTor+OK5L3n0Jodyh1w6IyZldzilCE/gF3gL8kR6qug10gRRzGY0JXuvalRs9o/swUMu1155UAV7gXfB2NNJ2vZYnIneNoEm1d7J2OqWgWrLdbbg="
=======
  - TEST=validation
  - TEST=pgsql
  - TEST=mysql
>>>>>>> responsive
language: php
php:
  - 5.3
python:
  - 3.3
addons:
  postgresql: "9.1"
git:
  # We have to init submodules ourselves to make it recursive
  submodules: false

before_install:
  # Start submodules
  - ./tools/startSubmodulesTRAVIS.sh

<<<<<<< HEAD
  # Install composer dependencies
  - cd lib/pkp && composer install && cd ../..

=======
>>>>>>> responsive
  # Configure the webserver
  - if [[ "$TEST" != "validation" ]]; then ./lib/pkp/tools/travis/prepare-webserver.sh; fi

  # Start xvfb
  - if [[ "$TEST" != "validation" ]]; then ./lib/pkp/tools/travis/start-xvfb.sh; fi

<<<<<<< HEAD
  # Start Selenium
  - if [[ "$TEST" != "validation" ]]; then ./lib/pkp/tools/travis/start-selenium.sh; fi

  # Prepare code coverage
  - if [[ "$TEST" == "mysql" ]]; then ./lib/pkp/tools/travis/prepare-code-coverage.sh; fi

=======
  # Configure firefox profile
  - if [[ "$TEST" != "validation" ]]; then ./lib/pkp/tools/travis/config-ff-profile.sh; fi

  # Start Selenium
  - if [[ "$TEST" != "validation" ]]; then ./lib/pkp/tools/travis/start-selenium.sh; fi

>>>>>>> responsive
  # Install the JS linter
  - if [[ "$TEST" == "validation" ]]; then ./lib/pkp/tools/travis/install-linter.sh; fi

  # Sleep and output our logs, to avoid hanging build with no access to
  # logs. This is useful for debugging but too verbose to leave enabled.
  # - (sleep 590; cat access.log; cat error.log; cat xvfb-output; cat selenium-output; cat ./lib/pkp/tests/results/error.log) &

script:
  - if [[ "$TEST" != "validation" ]]; then ./lib/pkp/tools/travis/run-tests.sh; fi
<<<<<<< HEAD
  # ./lib/tools/buildjs.sh not included in latter command pending stats porting
  - if [[ "$TEST" == "validation" ]]; then ./lib/pkp/tools/travis/validate-xml.sh && ./lib/pkp/tools/buildjs.sh; fi

after_script:
  # Merge the coverage reports into one HTML report and upload to http://pkp.sfu.ca/test-coverage
  - if [[ "$TEST" == "mysql" ]]; then ./lib/pkp/tools/travis/post-code-coverage.sh; fi
  # Print logs and outputs for debugging.
  # - cat access.log
  - cat error.log
=======
  - if [[ "$TEST" == "validation" ]]; then ./lib/pkp/tools/travis/validate-xml.sh; ./lib/pkp/tools/buildjs.sh; fi

after_script:
  # Print logs and outputs for debugging.
  # - cat access.log
  # - cat error.log
>>>>>>> responsive
  # - cat xvfb-output
  # - cat selenium-output
  - cat ./lib/pkp/tests/results/error.log
  - for f in lib/pkp/tests/results/*.png; do echo ============== START ${f} ================== ; cat $f | base64 ; echo ============== END ${f} ================== ; done
